version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-react
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node
